### ISSUE TITLE
The CG art on the game

### ISSUE THREAD

**Issue by gagantous** [wraithseeker/Visualnoveler#1]
Did you drew all the CG on the game since i cant find any information about that ( or maybe i was blinded ) ?

**Comment by wraithseeker** [comment]
Which game are you referring to? I am not the artist

**Comment by gagantous** [comment]
Destiny Chronicles and Ascendant Hearts

**Comment by wraithseeker** [comment]
Pierorabu and Thaichau

**Comment by gagantous** [comment]
Thanks (y)
